version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - restore_cache:
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Setup Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run:
          name: Run Tests and Coverage
          command: yarn test:ci
      - run:
          name: Run Linter
          command: yarn lint

workflows:
  version: 2
  test:
    jobs:
      - test
